name: 'Composer install'
description: 'Installs and caches PHP dependencies with Composer, accepting arguments to configure how and what to install.'
author: 'Benoît Chantre'

inputs:
  options:
    description: 'Composer install options'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Get Composer Cache Directory'
      id: 'composer-cache'
      shell: 'bash'
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: 'Configure Composer cache'
      uses: 'actions/cache@v4'
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          ${{ runner.os }}-composer-

    - name: 'Run Composer install'
      shell: 'bash'
      run: composer install --no-interaction --no-progress --ansi ${{ inputs.options }}

branding:
  icon: 'download'
  color: 'purple'
